config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :questions, only: [:show] do
    resources :answers, only: [:create]
  end
  resources :trips, only: [:create]

  get '/locations/street_address_from_lat_long' => 'locations#street_address_from_lat_long'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/chicago' => "welcome#index"

  root to: redirect('/chicago')

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_many :users_answers, through: :answers

  def next
    self.class.find_by(id: self[:id] + 1)
  end

  def answer_for(user)
    self.answers.joins(:users_answers).find_by(users_answers: {user: user})
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find(params[:id])
  end
end

app/helpers/question_helper.rb
module QuestionHelper
  def color_array
    ['green', 'blue', 'orange', 'purple', 'red', 'teal']
  end

  def randomize(colors)
    color = colors.shuffle.pop
    colors.delete(color)
    return color
  end


  def encouragement
    ['Keep Going!', "You're almost there!", "Just a few more!", "For Freedom!", "Some days you’re the pigeon; some days you’re the statue.", "Don't start no. Won't be no.", "There is always a light at the end of the tunnel. Sometimes it is a train."].sample
  end
end

app/views/questions/_prompt.html.erb
<%= form_tag question_answers_path(@question), class: "survey-question-form" do %>
<div class="question">
  <% colors = color_array %>
  <div class = "ui secondary black fluid button" id="question-asked"><h3><%= @question.content %></h3></div>
  <div class = 'answers'>

      <div class="ans"><%= submit_tag @question.answers[0].content, name: 'content', class: "button", id: selected_answer(@question.answers[0], current_user) %></div>

      <div class="ans"><%= submit_tag @question.answers[1].content, name: 'content', class: "button", id: selected_answer(@question.answers[1], current_user) %></div>

      <div class="ans"><%= submit_tag @question.answers[2].content, name: 'content', class: "button", id: selected_answer(@question.answers[2], current_user) %></div>

      <div class="ans"><%= submit_tag @question.answers[3].content, name: 'content', class: "button", id: selected_answer(@question.answers[3], current_user) %></div>

  </div>
</div>
<% end %>

<div class="ui icon message" id = "encouragement">
  <i class="notched circle loading icon"></i>
  <div class="content">
    <div class="header">
      Personalizing...
    </div>
    <p><%= encouragement %></p>
  </div>
</div>

<div class="survey-footer"><span id="qcount"><%= @question.id %> of 7</span><%= link_to "Take Later", root_path %></div>

app/views/questions/show.html.erb
<div id="question-form-container">
    <%= render 'prompt' %>
</div>