config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :questions, only: [:show] do
    resources :answers, only: [:create]
  end
  resources :trips, only: [:create]

  get '/locations/street_address_from_lat_long' => 'locations#street_address_from_lat_long'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/chicago' => "welcome#index"

  root to: redirect('/chicago')

end

app/views/layouts/_error_message.html.erb
<% if @user.errors.any? %>
  <div class = "ui negative message">
    <div class = 'header'>
    <%= render 'layouts/flash' %>
    </div>
    <ul class="list">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<div class="flash">
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div id='formula-pop-up'>
  <a id='close-pop-up'>x</a>
  <h3 id="header-pop-up">About the decisions...</h3>
  <div id='text-pop-up'>
    <p>We use the factors you think about to find the best mode for you:</p>
    <ul>
      <li><span class='leader'>Cost</span> - Ventra rates, gas, parking, Uber estimates/surge prices, cab fare estimate, etc.</li>
      <li><span class='leader'>Weather</span> - temperatute, precipitation, wind speed & direction</li>
      <li><span class='leader'>Distance</span> - your time and feet are valuable</li>
      <li><span class='leader'>Safety</span> - we take your concerns into account</li>
      <li><span class='leader'>Preferences</span> - register and take the survey for more personalization</li>
    </ul>
    <p class='bottom'>Pro tip: click a given route to open up the app you need!</p>
  </div>
</div>

<div class="ui inverted menu" id='nav-menu'>
  <div class="right menu">

    <li class='header-option item'><%= temp %>&deg;</li>

    <a href="#" class='header-option item' id="formula">Formula</a>


    <%if current_user%>
      <%= link_to "Logout", logout_path, method: :delete, class: "header-option item"%>
      <%= link_to "Profile", user_path(current_user), class: "header-option item"%>
    <% else %>
      <%= link_to "Login", login_path, class: "header-option item"%>
      <%= link_to "Register", new_user_path, class: "header-option item"%>
    <% end %>

  </div>
  <div class="left menu">
    <%=link_to image_tag(select_image , id:"logo"), root_path%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="user-scalable = yes">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Chango' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:700italic' rel='stylesheet' type='text/css'>


  <title>My<->Way</title>
</head>
<body>

  <div class="container">
    <%= render 'layouts/header' unless render_header%>
    <div class = "site-content">
      <%= yield %>
    </div>
  </div>
</body>
<footer>
</footer>
</html>